### ISSUE TITLE
Crash in RingRemovalFilter

### ISSUE THREAD

**Issue by samtygier-stfc** [mantidproject/mantidimaging#1032]
### Summary

Crash when Theta set too large

### Steps To Reproduce

Load a stack. In Operations, Ring Removal set Theta to a large number. I have seen it trigger at 305 on one data set but might need larger for others

### Expected Behaviour

Not crash

### Current Behaviour

Crash

### Context
Master running locally

### Failure Logs

```
#0  0x00007fffa7edec2d in mean_filter_fast_1D () at /home/sam/miniconda3/envs/mantidimaging-dev/lib/python3.8/site-packages/tomopy/util/extern/libtomopy-misc.so
#1  0x00007fffa7edf2da in ring_filter () at /home/sam/miniconda3/envs/mantidimaging-dev/lib/python3.8/site-packages/tomopy/util/extern/libtomopy-misc.so
#2  0x00007fffa7edf70f in remove_ring () at /home/sam/miniconda3/envs/mantidimaging-dev/lib/python3.8/site-packages/tomopy/util/extern/libtomopy-misc.so
#3  0x00007fff752059ed in ffi_call_unix64 () at /home/sam/miniconda3/envs/mantidimaging-dev/lib/python3.8/lib-dynload/../../libffi.so.7
#4  0x00007fff75205077 in ffi_call_int () at /home/sam/miniconda3/envs/mantidimaging-dev/lib/python3.8/lib-dynload/../../libffi.so.7
#5  0x00007fff7521a983 in _call_function_pointer
    (argtypecount=<optimised out>, argcount=14, resmem=0x7fff52ffbec0, restype=<optimised out>, atypes=0x7fff52ffbdc0, avalues=0x7fff52ffbe40, pProc=0x7fffa7edf470 <remove_ring>, flags=4353)
    at /usr/local/src/conda/python-3.8.10/Modules/_ctypes/callproc.c:921
#6  _ctypes_callproc (pProc=0x7fffa7edf470 <remove_ring>, argtuple=<optimised out>, flags=4353, argtypes=<optimised out>, restype=0x7fff44002090, checker=0x0)
    at /usr/local/src/conda/python-3.8.10/Modules/_ctypes/callproc.c:1264
#7  0x00007fff7521b334 in PyCFuncPtr_call (self=<optimised out>, inargs=<optimised out>, kwds=<optimised out>) at /usr/local/src/conda/python-3.8.10/Modules/_ctypes/_ctypes.c:4201
#8  0x0000555555686ebe in _PyObject_MakeTpCall (callable=0x7fff04124580, args=<optimised out>, nargs=<optimised out>, keywords=<optimised out>)
    at /home/conda/feedstock_root/build_artifacts/python-split_1620713755437/work/Python/errors.c:219
#9  0x0000555555728986 in _PyObject_Vectorcall (kwnames=0x0, nargsf=<optimised out>, args=0x7fff44001178, callable=0x7fff04124580)
    at /home/conda/feedstock_root/build_artifacts/python-split_1620713755437/work/Include/cpython/abstract.h:125
#10 _PyObject_Vectorcall (kwnames=0x0, nargsf=<optimised out>, args=0x7fff44001178, callable=0x7fff04124580)
    at /home/conda/feedstock_root/build_artifacts/python-split_1620713755437/work/Include/cpython/abstract.h:115
#11 call_function (kwnames=0x0, oparg=<optimised out>, pp_stack=<synthetic pointer>, tstate=0x55555971f300) at /home/conda/feedstock_root/build_artifacts/python-split_1620713755437/work/Python/ceval.c:4963
#12 _PyEval_EvalFrameDefault (f=<optimised out>, throwflag=<optimised out>) at /home/conda/feedstock_root/build_artifacts/python-split_1620713755437/work/Python/ceval.c:3469
#13 0x000055555570a433 in PyEval_EvalFrameEx (throwflag=0, f=0x7fff44000fe0) at /home/conda/feedstock_root/build_artifacts/python-split_1620713755437/work/Python/ceval.c:4298
#14 _PyEval_EvalCodeWithName
    (_co=<optimised out>, globals=<optimised out>, locals=<optimised out>, args=<optimised out>, argcount=<optimised out>, kwnames=<optimised out>, kwargs=<optimised out>, kwcount=<optimised out>, kwstep=<optimised out>, defs=<optimised out>, defcount=<optimised out>, kwdefs=<optimised out>, closure=<optimised out>, name=<optimised out>, qualname=<optimised out>)
    at /home/conda/feedstock_root/build_artifacts/python-split_1620713755437/work/Python/ceval.c:4298
#15 0x000055555570b818 in _PyFunction_Vectorcall (func=<optimised out>, stack=0x7fff040ad838, nargsf=<optimised out>, kwnames=<optimised out>)
    at /home/conda/feedstock_root/build_artifacts/python-split_1620713755437/work/Objects/call.c:436
#16 0x0000555555675b6e in PyVectorcall_Call (kwargs=<optimised out>, tuple=<optimised out>, callable=0x7fffa806d1f0)
    at /home/conda/feedstock_root/build_artifacts/python-split_1620713755437/work/Objects/call.c:200
#17 PyObject_Call (callable=0x7fffa806d1f0, args=<optimised out>, kwargs=<optimised out>) at /home/conda/feedstock_root/build_artifacts/python-split_1620713755437/work/Objects/call.c:228
#18 0x000055555572584f in do_call_core (kwdict=0x7fff0405d700, callargs=0x7fff040ad820, func=0x7fffa806d1f0, tstate=<optimised out>)
    at /home/conda/feedstock_root/build_artifacts/python-split_1620713755437/work/Python/ceval.c:5010
#19 _PyEval_EvalFrameDefault (f=<optimised out>, throwflag=<optimised out>) at /home/conda/feedstock_root/build_artifacts/python-split_1620713755437/work/Python/ceval.c:3559
#20 0x000055555570b646 in PyEval_EvalFrameEx (throwflag=0, f=0x7fff04114dd0) at /home/conda/feedstock_root/build_artifacts/python-split_1620713755437/work/Python/ceval.c:738
#21 function_code_fastcall (globals=<optimised out>, nargs=<optimised out>, args=<optimised out>, co=<optimised out>)
    at /home/conda/feedstock_root/build_artifacts/python-split_1620713755437/work/Objects/call.c:284
#22 _PyFunction_Vectorcall (func=<optimised out>, stack=<optimised out>, nargsf=<optimised out>, kwnames=<optimised out>)
    at /home/conda/feedstock_root/build_artifacts/python-split_1620713755437/work/Objects/call.c:411
--Type <RET> for more, q to quit, c to continue without paging--
#23 0x00005555557240f3 in _PyObject_Vectorcall (kwnames=0x0, nargsf=<optimised out>, args=0x7fff04114d80, callable=0x7fffc97b6310)
    at /home/conda/feedstock_root/build_artifacts/python-split_1620713755437/work/Include/cpython/abstract.h:115
#24 call_function (kwnames=0x0, oparg=<optimised out>, pp_stack=<synthetic pointer>, tstate=0x55555971f300) at /home/conda/feedstock_root/build_artifacts/python-split_1620713755437/work/Python/ceval.c:4963
#25 _PyEval_EvalFrameDefault (f=<optimised out>, throwflag=<optimised out>) at /home/conda/feedstock_root/build_artifacts/python-split_1620713755437/work/Python/ceval.c:3486
#26 0x000055555570b646 in PyEval_EvalFrameEx (throwflag=0, f=0x7fff04114be0) at /home/conda/feedstock_root/build_artifacts/python-split_1620713755437/work/Python/ceval.c:738
#27 function_code_fastcall (globals=<optimised out>, nargs=<optimised out>, args=<optimised out>, co=<optimised out>)
    at /home/conda/feedstock_root/build_artifacts/python-split_1620713755437/work/Objects/call.c:284
#28 _PyFunction_Vectorcall (func=<optimised out>, stack=<optimised out>, nargsf=<optimised out>, kwnames=<optimised out>)
    at /home/conda/feedstock_root/build_artifacts/python-split_1620713755437/work/Objects/call.c:411
#29 0x0000555555675b6e in PyVectorcall_Call (kwargs=<optimised out>, tuple=<optimised out>, callable=0x7fffc97b6700)
    at /home/conda/feedstock_root/build_artifacts/python-split_1620713755437/work/Objects/call.c:200
#30 PyObject_Call (callable=0x7fffc97b6700, args=<optimised out>, kwargs=<optimised out>) at /home/conda/feedstock_root/build_artifacts/python-split_1620713755437/work/Objects/call.c:228
#31 0x000055555572584f in do_call_core (kwdict=0x7fff0405d340, callargs=0x7fff040e18b0, func=0x7fffc97b6700, tstate=<optimised out>)
    at /home/conda/feedstock_root/build_artifacts/python-split_1620713755437/work/Python/ceval.c:5010
#32 _PyEval_EvalFrameDefault (f=<optimised out>, throwflag=<optimised out>) at /home/conda/feedstock_root/build_artifacts/python-split_1620713755437/work/Python/ceval.c:3559
#33 0x000055555570b646 in PyEval_EvalFrameEx (throwflag=0, f=0x7fff040623c0) at /home/conda/feedstock_root/build_artifacts/python-split_1620713755437/work/Python/ceval.c:738
#34 function_code_fastcall (globals=<optimised out>, nargs=<optimised out>, args=<optimised out>, co=<optimised out>)
    at /home/conda/feedstock_root/build_artifacts/python-split_1620713755437/work/Objects/call.c:284
#35 _PyFunction_Vectorcall (func=<optimised out>, stack=<optimised out>, nargsf=<optimised out>, kwnames=<optimised out>)
    at /home/conda/feedstock_root/build_artifacts/python-split_1620713755437/work/Objects/call.c:411
#36 0x00005555557240f3 in _PyObject_Vectorcall (kwnames=0x0, nargsf=<optimised out>, args=0x7fff041169b8, callable=0x7ffff73d8820)
    at /home/conda/feedstock_root/build_artifacts/python-split_1620713755437/work/Include/cpython/abstract.h:115
#37 call_function (kwnames=0x0, oparg=<optimised out>, pp_stack=<synthetic pointer>, tstate=0x55555971f300) at /home/conda/feedstock_root/build_artifacts/python-split_1620713755437/work/Python/ceval.c:4963
#38 _PyEval_EvalFrameDefault (f=<optimised out>, throwflag=<optimised out>) at /home/conda/feedstock_root/build_artifacts/python-split_1620713755437/work/Python/ceval.c:3486
#39 0x000055555570b646 in PyEval_EvalFrameEx (throwflag=0, f=0x7fff04116840) at /home/conda/feedstock_root/build_artifacts/python-split_1620713755437/work/Python/ceval.c:738
#40 function_code_fastcall (globals=<optimised out>, nargs=<optimised out>, args=<optimised out>, co=<optimised out>)
    at /home/conda/feedstock_root/build_artifacts/python-split_1620713755437/work/Objects/call.c:284
#41 _PyFunction_Vectorcall (func=<optimised out>, stack=<optimised out>, nargsf=<optimised out>, kwnames=<optimised out>)
    at /home/conda/feedstock_root/build_artifacts/python-split_1620713755437/work/Objects/call.c:411
#42 0x00005555557240f3 in _PyObject_Vectorcall (kwnames=0x0, nargsf=<optimised out>, args=0x7fff04062378, callable=0x7ffff73d8af0)
    at /home/conda/feedstock_root/build_artifacts/python-split_1620713755437/work/Include/cpython/abstract.h:115
#43 call_function (kwnames=0x0, oparg=<optimised out>, pp_stack=<synthetic pointer>, tstate=0x55555971f300) at /home/conda/feedstock_root/build_artifacts/python-split_1620713755437/work/Python/ceval.c:4963
#44 _PyEval_EvalFrameDefault (f=<optimised out>, throwflag=<optimised out>) at /home/conda/feedstock_root/build_artifacts/python-split_1620713755437/work/Python/ceval.c:3486
#45 0x000055555570b646 in PyEval_EvalFrameEx (throwflag=0, f=0x7fff04062200) at /home/conda/feedstock_root/build_artifacts/python-split_1620713755437/work/Python/ceval.c:738
#46 function_code_fastcall (globals=<optimised out>, nargs=<optimised out>, args=<optimised out>, co=<optimised out>)
    at /home/conda/feedstock_root/build_artifacts/python-split_1620713755437/work/Objects/call.c:284
#47 _PyFunction_Vectorcall (func=<optimised out>, stack=<optimised out>, nargsf=<optimised out>, kwnames=<optimised out>)
    at /home/conda/feedstock_root/build_artifacts/python-split_1620713755437/work/Objects/call.c:411
#48 0x000055555570bed1 in _PyObject_Vectorcall (kwnames=<optimised out>, nargsf=<optimised out>, args=<optimised out>, callable=<optimised out>)
    at /home/conda/feedstock_root/build_artifacts/python-split_1620713755437/work/Include/cpython/abstract.h:127
#49 method_vectorcall (method=<optimised out>, args=0x7ffff7677058, nargsf=<optimised out>, kwnames=<optimised out>)
    at /home/conda/feedstock_root/build_artifacts/python-split_1620713755437/work/Objects/classobject.c:89
#50 0x0000555555675b6e in PyVectorcall_Call (kwargs=<optimised out>, tuple=<optimised out>, callable=0x7fff06445a40)
    at /home/conda/feedstock_root/build_artifacts/python-split_1620713755437/work/Objects/call.c:200
#51 PyObject_Call (callable=0x7fff06445a40, args=<optimised out>, kwargs=<optimised out>) at /home/conda/feedstock_root/build_artifacts/python-split_1620713755437/work/Objects/call.c:228
#52 0x00005555557a9639 in t_bootstrap (boot_raw=0x7fff0405fd20) at /home/conda/feedstock_root/build_artifacts/python-split_1620713755437/work/Modules/_threadmodule.c:1002
#53 0x00005555557429c4 in pythread_wrapper (arg=<optimised out>) at /home/conda/feedstock_root/build_artifacts/python-split_1620713755437/work/Python/thread_pthread.h:232
#54 0x00007ffff7f8c609 in start_thread (arg=<optimised out>) at pthread_create.c:477
#55 0x00007ffff7d4e293 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

**Comment by samtygier-stfc** [comment]
Upstream https://github.com/tomopy/tomopy/issues/551
