### ISSUE TITLE
IndexError in do_preview_reconstruct_slice

### ISSUE THREAD

**Issue by samtygier-stfc** [mantidproject/mantidimaging#1105]
### Summary

IndexError when a stack is open in the recon window, and then cropped in the operations window, such that the current slice is no longer valid

### Steps To Reproduce

Open a stack in the recon window.
Select a slice near the bottom of the projection
Open the operations window
Crop the stack

### Expected Behaviour

Recon window chooses a new in bounds slice

### Current Behaviour

```
Traceback (most recent call last):
  File "/home/sam/git/mantidimaging/mantidimaging/gui/dialogs/async_task/model.py", line 50, in _on_task_exit
    self.on_complete_function(self.task)
  File "/home/sam/git/mantidimaging/mantidimaging/gui/windows/recon/presenter.py", line 323, in completed
    self._set_precalculated_cor_tilt(cor, tilt)
  File "/home/sam/git/mantidimaging/mantidimaging/gui/windows/recon/presenter.py", line 307, in _set_precalculated_cor_tilt
    self.do_preview_reconstruct_slice()
  File "/home/sam/git/mantidimaging/mantidimaging/gui/windows/recon/presenter.py", line 208, in do_preview_reconstruct_slice
    self.view.update_sinogram(self.model.images.sino(slice_idx))
  File "/home/sam/git/mantidimaging/mantidimaging/core/data/images.py", line 186, in sino
    return np.swapaxes(self.data, 0, 1)[slice_idx]
IndexError: index 186 is out of bounds for axis 0 with size 161
2021-08-17 15:52:58,305 [mantidimaging.gui.windows.main.view:L365] ERROR: Traceback (most recent call last):
  File "/home/sam/git/mantidimaging/mantidimaging/gui/dialogs/async_task/model.py", line 50, in _on_task_exit
    self.on_complete_function(self.task)
  File "/home/sam/git/mantidimaging/mantidimaging/gui/windows/recon/presenter.py", line 323, in completed
    self._set_precalculated_cor_tilt(cor, tilt)
  File "/home/sam/git/mantidimaging/mantidimaging/gui/windows/recon/presenter.py", line 307, in _set_precalculated_cor_tilt
    self.do_preview_reconstruct_slice()
  File "/home/sam/git/mantidimaging/mantidimaging/gui/windows/recon/presenter.py", line 208, in do_preview_reconstruct_slice
    self.view.update_sinogram(self.model.images.sino(slice_idx))
  File "/home/sam/git/mantidimaging/mantidimaging/core/data/images.py", line 186, in sino
    return np.swapaxes(self.data, 0, 1)[slice_idx]
IndexError: index 186 is out of bounds for axis 0 with size 161

```
Also the exception here leaves the recon window in an unusable state.

### Context

Current master

**Comment by samtygier-stfc** [comment]
I can't reproduce in current mantid imaging, looks like other changes have resolved it
