### ISSUE TITLE
ImportError: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found

### ISSUE THREAD

**Issue by samtygier-stfc** [mantidproject/mantidimaging#1228]
### Summary

On Ubuntu 18.04 running Mantid Imaging, when `scipy.interpolate` is imported:

`ImportError: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version ``GLIBCXX_3.4.26' not found (required by /root/mambaforge/envs/test/lib/python3.10/site-packages/scipy/interpolate/_rbfinterp_pythran.cpython-310-x86_64-linux-gnu.so)`

### Steps To Reproduce

Can be reproduced with just scipy (from conda-forge) and pyqt5 (from pip)

```
conda create -n test
conda activate test
conda install scipy
pip install pyqt5
python -c "import PyQt5.QtCore; import scipy.interpolate"
```
gives

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/root/mambaforge/envs/test/lib/python3.10/site-packages/scipy/interpolate/__init__.py", line 174, in <module>
    from ._rbfinterp import *
  File "/root/mambaforge/envs/test/lib/python3.10/site-packages/scipy/interpolate/_rbfinterp.py", line 11, in <module>
    from ._rbfinterp_pythran import _build_system, _evaluate, _polynomial_matrix
ImportError: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /root/mambaforge/envs/test/lib/python3.10/site-packages/scipy/interpolate/_rbfinterp_pythran.cpython-310-x86_64-linux-gnu.so
```
interestingly
`python -c "import scipy.interpolate; import PyQt5.QtCore"`
works fine.

`ldd /root/mambaforge/envs/test/lib/python3.10/site-packages/scipy/interpolate/_rbfinterp_pythran.cpython-310-x86_64-linux-gnu.so`
shows
`libstdc++.so.6 => /root/mambaforge/envs/test/lib/python3.10/site-packages/scipy/interpolate/../../../../libstdc++.so.6 (0x00007ff1c602f000)`

but `ldd /root/mambaforge/envs/test/lib/python3.10/site-packages/PyQt5/QtCore.abi3.so`
shows
`libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fbe6aacd000)`

So if PyQt is imported first, then the older system libstdc++ is loaded.

Explicitly setting `export LD_LIBRARY_PATH=/root/mambaforge/lib/` is a workaround.

**Comment by samtygier-stfc** [comment]
We no longer use qt from pip, so hopefully won't see this again.
