### ISSUE TITLE
System tests: test_correlate ValueError

### ISSUE THREAD

**Issue by samtygier-stfc** [mantidproject/mantidimaging#1251]
### Summary

Intermittent failure in the gui system tests
`ValueError: Could not find button 'Yes' in ['OK']`

### Steps To Reproduce
Seems intermittent, log here.
https://github.com/mantidproject/mantidimaging/runs/4773539900?check_suite_focus=true

### Failure Logs

```
 mantidimaging/gui/test/test_gui_system_reconstruction.py::TestGuiSystemReconstruction::test_correlate Loading: [======================================================================]1/1
Loading: [===============================================-----------------------]2/3
Traceback (most recent call last):
  File "/home/runner/work/mantidimaging/mantidimaging/mantidimaging/gui/test/gui_system_base.py", line 42, in <lambda>
    QTimer.singleShot(SHORT_DELAY, lambda: self._click_messageBox("Yes"))
  File "/home/runner/work/mantidimaging/mantidimaging/mantidimaging/gui/test/gui_system_base.py", line 56, in _click_messageBox
    raise ValueError(f"Could not find button '{button_text}' in {button_texts}")
ValueError: Could not find button 'Yes' in ['OK']
Error: The action has timed out.
```

**Comment by samtygier-stfc** [comment]
Sometimes triggers locally with:
'xvfb-run --auto-servernum python -m pytest -vs -rs --run-system-tests -k test_correlate'

**Comment by samtygier-stfc** [comment]
Error message means that when GuiSystemBase.tearDown() is called, it tries to press a "Yes" button in a visible QMessageBox, but instead finds a message box with only an OK in it.

**Comment by samtygier-stfc** [comment]
I am still seeing a similar issue, so more debugging at #1254

**Comment by samtygier-stfc** [comment]
```
 mantidimaging/gui/test/test_gui_system_reconstruction.py::TestGuiSystemReconstruction::test_correlate 
TestGuiSystemReconstruction:test_correlate start
Loading: [======================================================================]1/1
Loading: [===============================================-----------------------]2/3
Traceback (most recent call last):
  File "/home/runner/work/mantidimaging/mantidimaging/mantidimaging/gui/dialogs/async_task/task.py", line 44, in run
    self.result = call_with_known_parameters(self.task_function, **self.kwargs)
  File "/home/runner/work/mantidimaging/mantidimaging/mantidimaging/core/utility/func_call.py", line 11, in call_with_known_parameters
    return func(**ka)
  File "/home/runner/work/mantidimaging/mantidimaging/mantidimaging/gui/windows/recon/model.py", line 136, in run_preview_recon
    recon.data[0] = reconstructor.single_sino(self.images.sino(slice_idx),
AttributeError: 'NoneType' object has no attribute 'sino'
Traceback (most recent call last):
  File "/home/runner/work/mantidimaging/mantidimaging/mantidimaging/gui/test/gui_system_base.py", line 50, in <lambda>
    QTimer.singleShot(SHORT_DELAY, lambda: self._click_messageBox("Yes"))
  File "/home/runner/work/mantidimaging/mantidimaging/mantidimaging/gui/test/gui_system_base.py", line 64, in _click_messageBox
    raise ValueError(f"Could not find button '{button_text}' in {button_texts}.\n"
ValueError: Could not find button 'Yes' in ['OK'].
Message box: Error Encountered error while trying to reconstruct: 'NoneType' object has no attribute 'sino'
```

**Comment by samtygier-stfc** [comment]
This is happening because `self.images` is None at `recon/model.py` line 136 even though it was a valid Images on the lines before. A sleep on the line before 136 makes this easier to trigger.

`self.images` is a property and triggers a lookup `MainWindowPresenter.active_stacks()`. If the stacks are deleted while `run_preview_recon()` is running, then self.images will become none. This is happening because the test `tearDown()` method is being called before everything has finished, and calls `_close_stack_tabs`.

We do wait until the correlation has finished (until the button is enabled again), but after it has completed we call `self._set_precalculated_cor_tilt` with the result, which calls `do_preview_reconstruct_slice` this triggers another async call which we don't wait for.
