### ISSUE TITLE
TestGuiSystemReconstruction::test_refine : RuntimeError: dictionary changed size during iteration

### ISSUE THREAD

**Issue by samtygier-stfc** [mantidproject/mantidimaging#1359]
### Summary

This seems to be a common cause of hangs in the gui system tests. Now that we are letting the tests run for longer we see the message.

### Steps To Reproduce

Happens on github actions testing

### Current Behaviour

This causes the test to hang until the timeout

### Context

First seen in Feb

### Failure Logs

```
 mantidimaging/gui/test/gui_system_reconstruction_test.py::TestGuiSystemReconstruction::test_refine Loading: [======================================================================]1/1
Loading: [===============================================-----------------------]2/3
Traceback (most recent call last):
  File "/home/runner/work/mantidimaging/mantidimaging/mantidimaging/gui/windows/recon/presenter.py", line 100, in notify
    self._do_refine_selected_cor()
  File "/home/runner/work/mantidimaging/mantidimaging/mantidimaging/gui/windows/recon/presenter.py", line 271, in _do_refine_selected_cor
    dialog = CORInspectionDialogView(self.view, self.model.images, slice_idx, self.model.last_cor,
  File "/home/runner/work/mantidimaging/mantidimaging/mantidimaging/gui/dialogs/cor_inspection/view.py", line 53, in __init__
    self.image_canvas = CompareSlicesView(self)
  File "/home/runner/work/mantidimaging/mantidimaging/mantidimaging/gui/dialogs/cor_inspection/recon_slice_view.py", line 22, in __init__
    self.imageview_current = MIMiniImageView(name="current")
  File "/home/runner/work/mantidimaging/mantidimaging/mantidimaging/gui/widgets/mi_mini_image_view/view.py", line 35, in __init__
    self.vb = ViewBox(invertY=True, lockAspect=True, name=name)
  File "/usr/share/miniconda3/envs/mantidimaging-dev/lib/python3.8/site-packages/pyqtgraph/graphicsItems/ViewBox/ViewBox.py", line 234, in __init__
    self.register(name)
  File "/usr/share/miniconda3/envs/mantidimaging-dev/lib/python3.8/site-packages/pyqtgraph/graphicsItems/ViewBox/ViewBox.py", line 267, in register
    ViewBox.updateAllViewLists()
  File "/usr/share/miniconda3/envs/mantidimaging-dev/lib/python3.8/site-packages/pyqtgraph/graphicsItems/ViewBox/ViewBox.py", line 1711, in updateAllViewLists
    for v in ViewBox.AllViews:
  File "/usr/share/miniconda3/envs/mantidimaging-dev/lib/python3.8/weakref.py", line 438, in keys
    for wr in self.data:
RuntimeError: dictionary changed size during iteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/mantidimaging/mantidimaging/mantidimaging/gui/test/gui_system_reconstruction_test.py", line 66, in <lambda>
    QTimer.singleShot(SHORT_DELAY, lambda: self._click_cor_inspect())
  File "/home/runner/work/mantidimaging/mantidimaging/mantidimaging/gui/test/gui_system_reconstruction_test.py", line 54, in _click_cor_inspect
    cls._wait_for_widget_visible(CORInspectionDialogView)
  File "/home/runner/work/mantidimaging/mantidimaging/mantidimaging/gui/test/gui_system_base.py", line 90, in _wait_for_widget_visible
    raise RuntimeError("_wait_for_stack_selector reach max retries")
RuntimeError: _wait_for_stack_selector reach max retries
```

**Comment by samtygier-stfc** [comment]
Not seen in a while
