### ISSUE TITLE
test_refine_stress: _completed_finding_cors TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by samtygier-stfc** [mantidproject/mantidimaging#1442]
### Summary

In intermittent test failure on github actions.

`ERROR at teardown of TestGuiSystemReconstruction.test_refine`

```
   File "D:\a\mantidimaging\mantidimaging\mantidimaging\gui\windows\recon\presenter.py", line 383, in _completed_finding_cors
    for slice_idx, cor in zip(slice_indices, cors):
TypeError: 'NoneType' object is not iterable
```

### Current Behaviour

Crash

### Context

Seen as far back as 2022-01-27 . Occurs on Conda and Windows tests.
E.g. https://github.com/mantidproject/mantidimaging/runs/6302334316?check_suite_focus=true

### Failure Logs

```
 ERROR    mantidimaging.gui.dialogs.async_task.task:task.py:52 Failed to execute task
Traceback (most recent call last):
  File "D:\a\mantidimaging\mantidimaging\mantidimaging\gui\dialogs\async_task\task.py", line 49, in run
    self.result = call_with_known_parameters(self.task_function, **self.kwargs)
  File "D:\a\mantidimaging\mantidimaging\mantidimaging\core\utility\func_call.py", line 11, in call_with_known_parameters
    return func(**ka)
  File "D:\a\mantidimaging\mantidimaging\mantidimaging\gui\windows\recon\model.py", line 261, in auto_find_minimisation_sqsum
    cor = reconstructor.find_cor(self.images, slice, initial_cor[idx], recon_params)
  File "D:\a\mantidimaging\mantidimaging\mantidimaging\core\reconstruct\tomopy_recon.py", line 22, in find_cor
    return tomopy.find_center(images.sinograms,
  File "C:\Miniconda3\envs\mantidimaging-dev\lib\site-packages\tomopy\recon\rotation.py", line 146, in find_center
    res = minimize(
  File "C:\Miniconda3\envs\mantidimaging-dev\lib\site-packages\scipy\optimize\_minimize.py", line 611, in minimize
    return _minimize_neldermead(fun, x0, args, callback, bounds=bounds,
  File "C:\Miniconda3\envs\mantidimaging-dev\lib\site-packages\scipy\optimize\optimize.py", line 750, in _minimize_neldermead
    fsim[k] = func(sim[k])
  File "C:\Miniconda3\envs\mantidimaging-dev\lib\site-packages\scipy\optimize\optimize.py", line 464, in function_wrapper
    return function(np.copy(x), *(wrapper_args + args))
  File "C:\Miniconda3\envs\mantidimaging-dev\lib\site-packages\tomopy\recon\rotation.py", line 201, in _find_center_cost
    hist, e = np.histogram(rec, bins=64, range=[hmin, hmax])
  File "<__array_function__ internals>", line 5, in histogram
  File "C:\Miniconda3\envs\mantidimaging-dev\lib\site-packages\numpy\lib\histograms.py", line 792, in histogram
    bin_edges, uniform_bins = _get_bin_edges(a, bins, range, weights)
  File "C:\Miniconda3\envs\mantidimaging-dev\lib\site-packages\numpy\lib\histograms.py", line 426, in _get_bin_edges
    first_edge, last_edge = _get_outer_edges(a, range)
  File "C:\Miniconda3\envs\mantidimaging-dev\lib\site-packages\numpy\lib\histograms.py", line 315, in _get_outer_edges
    raise ValueError(
ValueError: supplied range of [nan, nan] is not finite
ERROR    mantidimaging.gui.dialogs.async_task.model:model.py:63 Failed to run task completion callback
Traceback (most recent call last):
  File "D:\a\mantidimaging\mantidimaging\mantidimaging\gui\dialogs\async_task\model.py", line 61, in _on_task_exit
    self.on_complete_function(self.task)
  File "D:\a\mantidimaging\mantidimaging\mantidimaging\gui\windows\recon\presenter.py", line 383, in _completed_finding_cors
    for slice_idx, cor in zip(slice_indices, cors):
TypeError: 'NoneType' object is not iterable
```

**Comment by rbauststfc** [comment]
Looking further down the logs gives this error:

```
___________________ TestGuiSystemReconstruction.test_refine ___________________

self = <mantidimaging.gui.test.gui_system_reconstruction_test.TestGuiSystemReconstruction testMethod=test_refine>

    def test_refine(self):
        QTimer.singleShot(SHORT_DELAY, lambda: self._click_InputDialog(set_int=4))
        QTest.mouseClick(self.recon_window.minimiseBtn, Qt.MouseButton.LeftButton)
>       wait_until(lambda: self.recon_window.minimiseBtn.isEnabled(), max_retry=200)

mantidimaging\gui\test\gui_system_reconstruction_test.py:66: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

test_func = <function TestGuiSystemReconstruction.test_refine.<locals>.<lambda> at 0x00000[238](https://github.com/mantidproject/mantidimaging/runs/6302334316?check_suite_focus=true#step:14:238)FA27D670>
delay = 0.1, max_retry = 200

    def wait_until(test_func: Callable[[], bool], delay=0.1, max_retry=100):
        """
        Repeat test_func every delay seconds until is becomes true. Or if max_retry is reached return false.
        """
        for _ in range(max_retry):
            if test_func():
                return True
            QTest.qWait(int(delay * 1000))
>       raise RuntimeError("wait_until reach max retries")
E       RuntimeError: wait_until reach max retries

mantidimaging\test_helpers\qt_test_helpers.py:17: RuntimeError
------------------------------ Captured log call ------------------------------
ERROR    mantidimaging.gui.dialogs.async_task.task:task.py:52 Failed to execute task
Traceback (most recent call last):
  File "D:\a\mantidimaging\mantidimaging\mantidimaging\gui\dialogs\async_task\task.py", line 49, in run
    self.result = call_with_known_parameters(self.task_function, **self.kwargs)
  File "D:\a\mantidimaging\mantidimaging\mantidimaging\core\utility\func_call.py", line 11, in call_with_known_parameters
    return func(**ka)
  File "D:\a\mantidimaging\mantidimaging\mantidimaging\gui\windows\recon\model.py", line [261](https://github.com/mantidproject/mantidimaging/runs/6302334316?check_suite_focus=true#step:14:261), in auto_find_minimisation_sqsum
    cor = reconstructor.find_cor(self.images, slice, initial_cor[idx], recon_params)
  File "D:\a\mantidimaging\mantidimaging\mantidimaging\core\reconstruct\tomopy_recon.py", line 22, in find_cor
    return tomopy.find_center(images.sinograms,
  File "C:\Miniconda3\envs\mantidimaging-dev\lib\site-packages\tomopy\recon\rotation.py", line 146, in find_center
    res = minimize(
  File "C:\Miniconda3\envs\mantidimaging-dev\lib\site-packages\scipy\optimize\_minimize.py", line 611, in minimize
    return _minimize_neldermead(fun, x0, args, callback, bounds=bounds,
  File "C:\Miniconda3\envs\mantidimaging-dev\lib\site-packages\scipy\optimize\optimize.py", line 750, in _minimize_neldermead
    fsim[k] = func(sim[k])
  File "C:\Miniconda3\envs\mantidimaging-dev\lib\site-packages\scipy\optimize\optimize.py", line 464, in function_wrapper
    return function(np.copy(x), *(wrapper_args + args))
  File "C:\Miniconda3\envs\mantidimaging-dev\lib\site-packages\tomopy\recon\rotation.py", line 201, in _find_center_cost
    hist, e = np.histogram(rec, bins=64, range=[hmin, hmax])
  File "<__array_function__ internals>", line 5, in histogram
  File "C:\Miniconda3\envs\mantidimaging-dev\lib\site-packages\numpy\lib\histograms.py", line 792, in histogram
    bin_edges, uniform_bins = _get_bin_edges(a, bins, range, weights)
  File "C:\Miniconda3\envs\mantidimaging-dev\lib\site-packages\numpy\lib\histograms.py", line 426, in _get_bin_edges
    first_edge, last_edge = _get_outer_edges(a, range)
  File "C:\Miniconda3\envs\mantidimaging-dev\lib\site-packages\numpy\lib\histograms.py", line 315, in _get_outer_edges
    raise ValueError(
ValueError: supplied range of [nan, nan] is not finite
ERROR    mantidimaging.gui.dialogs.async_task.model:model.py:63 Failed to run task completion callback
Traceback (most recent call last):
  File "D:\a\mantidimaging\mantidimaging\mantidimaging\gui\dialogs\async_task\model.py", line 61, in _on_task_exit
    self.on_complete_function(self.task)
  File "D:\a\mantidimaging\mantidimaging\mantidimaging\gui\windows\recon\presenter.py", line 383, in _completed_finding_cors
    for slice_idx, cor in zip(slice_indices, cors):
TypeError: 'NoneType' object is not iterable
```

It looked like this might be related to timing issues we've seen previously and this was investigated under #1455, however increasing the timeouts for `test_refine` and `test_refine_stress` don't seem to make things any better. This problem appears to affect `test_refine`, `test_refine_stress` and `test_minimise` intermittently.

**Comment by samtygier-stfc** [comment]
I think what is happening is that something goes wrong (the TypeError) in `_completed_finding_cors` and is not handled well. So the redraw fails (the ValueError). And because the operation never completes the button never gets re-enabled, so then it hits the timeout.

**Comment by samtygier-stfc** [comment]
Happens in tomopy's gridrec. To reproduce locally you need to force tomopy

```diff
--- a/mantidimaging/gui/windows/recon/view.py
+++ b/mantidimaging/gui/windows/recon/view.py
@@ -85,7 +85,7 @@ class ReconstructWindowView(BaseMainWindowView):
         self.main_window = main_window
         self.presenter = ReconstructWindowPresenter(self, main_window)
 
-        if CudaChecker().cuda_is_present():
+        if False:
             self.algorithmName.insertItem(0, "FBP_CUDA")
             self.algorithmName.insertItem(1, "SIRT_CUDA")
             self.algorithmName.insertItem(2, "CIL: PDHG-TV")
```

**Comment by samtygier-stfc** [comment]
Might be fixed by #1476
