### ISSUE TITLE
Use conda-forge package for pyqt

### ISSUE THREAD

**Issue by samtygier-stfc** [mantidproject/mantidimaging#1598]
### Desired Behaviour

There are now conda packages for pyqt so we can switch over from the pip packages.

See if it is possible to switch pyqtgraph as well.

**Comment by samtygier-stfc** [comment]
I actually hit an issue in the applitools tests which seems to be caused by mixing conda and pip packages today, triggered by a recent update to llvmlite (from numba) which now uses llvm-11. Hopefully moving to the conda package will prevent it happening for us.

In am conda env with pyqt5 5.15.7 from pip and llvmlite 0.39.1 from conda, if qt is imported before llvmlite I get the error:

```
Traceback (most recent call last):
  File "/home/sam/mambaforge/envs/mantidimaging-dev/lib/python3.9/site-packages/llvmlite/binding/ffi.py", line 160, in <module>
    lib = ctypes.CDLL(str(_lib_handle.__enter__()))
  File "/home/sam/mambaforge/envs/mantidimaging-dev/lib/python3.9/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by /home/sam/mambaforge/envs/mantidimaging-dev/lib/python3.9/site-packages/llvmlite/binding/../../../../libLLVM-11.so)
```

`python -c "from PyQt5.QtCore import Qt; from llvmlite.binding import ffi"`
crashes

`python -c "from llvmlite.binding import ffi; from PyQt5.QtCore import Qt"`
is ok

Testing in a clean ubuntu 20.04 docker with mambaforge, I get the same issue with

```
apt-get update && apt-get install libglib2.0-0
mamba create -n test-mixed python=3.9 llvmlite
mamba activate test-mixed
pip install pyqt5
```

but don't see it with
```
mamba create -n test python=3.9 llvmlite pyqt=5.15
mamba activate test
```
