### ISSUE TITLE
ValueError: Numpy array should be float32 in single_sino

### ISSUE THREAD

**Issue by samtygier-stfc** [mantidproject/mantidimaging#1748]
### Summary

Error reported while using the reconstruction window in CIL mode. Possibly related to running Ring Removal (if its stripe removal could be due to auto sinogram conversion).

From logs looks like is is in 1D array, maybe angles? Maybe from changes for golden angle.

Reported by an IMAT user

### Context

Unstable on IDAaaS

### Failure Logs

```
2023-03-24 10:48:12,355 [mantidimaging.gui.dialogs.async_task.task:L53] ERROR: Failed to execute task: Numpy array should be float32
Traceback (most recent call last):
  File "/opt/mambaforge/envs/mantidimaging_unstable/lib/python3.9/site-packages/mantidimaging/gui/dialogs/async_task/task.py", line 50, in run
    self.result = call_with_known_parameters(self.task_function, **self.kwargs)
  File "/opt/mambaforge/envs/mantidimaging_unstable/lib/python3.9/site-packages/mantidimaging/core/utility/func_call.py", line 12, in call_with_known_parameters
    return func(**ka)
  File "/opt/mambaforge/envs/mantidimaging_unstable/lib/python3.9/site-packages/mantidimaging/gui/windows/recon/model.py", line 143, in run_preview_recon
    recon.data[0] = reconstructor.single_sino(images.sino(slice_idx),
  File "/opt/mambaforge/envs/mantidimaging_unstable/lib/python3.9/site-packages/mantidimaging/core/reconstruct/cil_recon.py", line 194, in single_sino
    algo.next()
  File "/opt/mambaforge/envs/mantidimaging_unstable/lib/python3.9/site-packages/cil/optimisation/algorithms/Algorithm.py", line 100, in next
    return self.__next__()
  File "/opt/mambaforge/envs/mantidimaging_unstable/lib/python3.9/site-packages/cil/optimisation/algorithms/Algorithm.py", line 111, in __next__
    self.update_objective()
  File "/opt/mambaforge/envs/mantidimaging_unstable/lib/python3.9/site-packages/cil/optimisation/algorithms/PDHG.py", line 486, in update_objective
    self.operator.direct(self.x_old, out=self.y_tmp)
  File "/opt/mambaforge/envs/mantidimaging_unstable/lib/python3.9/site-packages/cil/optimisation/operators/BlockOperator.py", line 187, in direct
    self.get_item(row,col).direct(
  File "/opt/mambaforge/envs/mantidimaging_unstable/lib/python3.9/site-packages/cil/plugins/astra/operators/ProjectionOperator.py", line 159, in direct
    return self.operator.direct(IM, out=out)
  File "/opt/mambaforge/envs/mantidimaging_unstable/lib/python3.9/site-packages/cil/plugins/astra/operators/AstraProjector3D.py", line 71, in direct
    temp= self.fp.get_output(out = out)
  File "/opt/mambaforge/envs/mantidimaging_unstable/lib/python3.9/site-packages/cil/framework/framework.py", line 3745, in get_output
    self.process(out=out)
  File "/opt/mambaforge/envs/mantidimaging_unstable/lib/python3.9/site-packages/cil/plugins/astra/processors/AstraForwardProjector3D.py", line 100, in process
    sinogram_id = astra.data3d.link('-sino', self.proj_geom, arr_out)
  File "/opt/mambaforge/envs/mantidimaging_unstable/lib/python3.9/site-packages/astra/data3d.py", line 60, in link
    checkArrayForLink(data)
  File "/opt/mambaforge/envs/mantidimaging_unstable/lib/python3.9/site-packages/astra/pythonutils.py", line 76, in checkArrayForLink
    raise ValueError("Numpy array should be float32")
ValueError: Numpy array should be float32
```
In the logs I also see
```
2023-03-24 10:45:06,156 [mantidimaging.core.parallel.utility:L47] INFO: Requested shared array with shape=(1, 719, 719), size=2067844, dtype=float32
2023-03-24 10:45:13,900 [mantidimaging.core.parallel.utility:L47] INFO: Requested shared array with shape=(1775,), size=7100, dtype=<class 'numpy.float32'>
2023-03-24 10:45:13,901 [mantidimaging.core.parallel.utility:L47] INFO: Requested shared array with shape=(721, 1775), size=5119100, dtype=<class 'numpy.float32'>
2023-03-24 10:45:13,901 [mantidimaging.core.parallel.utility:L47] INFO: Requested shared array with shape=(721,), size=2884, dtype=<class 'numpy.int32'>
2023-03-24 10:45:13,901 [mantidimaging.core.parallel.utility:L47] INFO: Requested shared array with shape=(2, 1775, 719), size=10209800, dtype=<class 'numpy.float32'>
```
~which is possibly where the int32 array is being created.~ These are created in `polyfit_correlation.find_center()` so I don't think they are related to the issue.

**Comment by samtygier-stfc** [comment]
I can trigger this by loading selecting a Pixel Bit Depth of float64 in the Load Dataset dialog.

Only effects CIL
