### ISSUE TITLE
TypeError when saving images with a log file

### ISSUE THREAD

**Issue by samtygier-stfc** [mantidproject/mantidimaging#1779]
### Summary

Error occurs when saving an image stack as images. Possibly only if the image stack has a log loaded.

`TypeError: Object of type PosixPath is not JSON serializable`

### Steps To Reproduce

File -> Load Dataset
Select the standard flower dataset
Make sure the Sample log is selected and ticked

File -> Save as Image Files
Choose a directory. Click Save All

### Expected Behaviour
Saves successfully

### Current Behaviour

Error message, See below for backtrace

### Context
Current main. Happens on IDAaaS and locally

Probably happening since changes around filenames made the log attribute of the image stack into a Path. May just need to convert it to a string before writing to json.

### Failure Logs

```
Traceback (most recent call last):
  File "/home/sam/git/mantidimaging/mantidimaging/gui/dialogs/async_task/task.py", line 50, in run
    self.result = call_with_known_parameters(self.task_function, **self.kwargs)
  File "/home/sam/git/mantidimaging/mantidimaging/core/utility/func_call.py", line 12, in call_with_known_parameters
    return func(**ka)
  File "/home/sam/git/mantidimaging/mantidimaging/gui/windows/main/model.py", line 73, in do_images_saving
    filenames = saver.image_save(images,
  File "/home/sam/git/mantidimaging/mantidimaging/core/io/saver.py", line 134, in image_save
    images.save_metadata(f, rescale_params)
  File "/home/sam/git/mantidimaging/mantidimaging/core/data/imagestack.py", line 116, in save_metadata
    json.dump(self.metadata, f, indent=4)
  File "/home/sam/mambaforge/envs/mantidimaging-dev/lib/python3.9/json/__init__.py", line 179, in dump
    for chunk in iterable:
  File "/home/sam/mambaforge/envs/mantidimaging-dev/lib/python3.9/json/encoder.py", line 431, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/home/sam/mambaforge/envs/mantidimaging-dev/lib/python3.9/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/home/sam/mambaforge/envs/mantidimaging-dev/lib/python3.9/json/encoder.py", line 438, in _iterencode
    o = _default(o)
  File "/home/sam/mambaforge/envs/mantidimaging-dev/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type PosixPath is not JSON serializable

```

**Comment by samtygier-stfc** [comment]
Similar issue in Image -> Show history and metadata, and then click copy.
