### ISSUE TITLE
ModuleNotFoundError: No module named 'rotate_stack'

### ISSUE THREAD

**Issue by samtygier-stfc** [mantidproject/mantidimaging#1918]
### Summary

When running an operation some of the works are unable to import the module.

### Steps To Reproduce

Start MI
Open a dataset, open operations
Run Rotate Stack, with angle non-zero

### Expected Behaviour

Operations runs

### Current Behaviour
Error message

### Context

Seen on IDAaaS on Tomography Advanced large
MI 2.6.0a1.post238 and 2.6.0a1.post253
Both on Winfried and Sam's logins (intermittently)

### Failure Logs

```
Traceback (most recent call last):
  File "/opt/mambaforge/envs/mantidimaging_unstable/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/opt/mambaforge/envs/mantidimaging_unstable/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/mambaforge/envs/mantidimaging_unstable/lib/python3.10/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/opt/mambaforge/envs/mantidimaging_unstable/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/opt/mambaforge/envs/mantidimaging_unstable/lib/python3.10/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
  File "/opt/mambaforge/envs/mantidimaging_unstable/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/mambaforge/envs/mantidimaging_unstable/lib/python3.10/multiprocessing/pool.py", line 114, in worker
    task = get()
ModuleNotFoundError: No module named 'rotate_stack'
```

**Comment by samtygier-stfc** [comment]
This is probably because the initialisation code that calls `load_filter_packages()` has not run in all multiprocessing pool workers. 

We use:
```python
    pool = context.Pool(cores)
    pool.map(worker_setup, range(cores))
```
For a small number of cores, this will usually mean that each worker gets allocated to run `worker_setup()`, so was sufficient in testing.

On the larger instances on IDAaaS, a worker might complete `worker_setup()` before all the tasks have been started, so some worker will run the function multiple times, and some wont run it at all.
