### ISSUE TITLE
Spectrum viewer: error renaming ROI before a table change

### ISSUE THREAD

**Issue by samtygier-stfc** [mantidproject/mantidimaging#1920]
### Summary

When renaming the first ROI in the spectrum viewer, before performing any other action on the ROI table, the rename fails with a `KeyError`.

This happens in `SpectrumViewerWindowView` because the initial value of `self.current_roi` is `""`. 

If we rename in the GUI the ROI before doing anything else, then in on_data_in_table_change()
```
    if self.current_roi in ["", " "]:
        self.current_roi = selected_row_data[0]
```
Now the new name matches self.current_roi, so we don't bother doing the rename.

If another action is done before this, e.g. toggle viability, or change row selection (by adding an ROI), then `self.current_roi` get set.

### Steps To Reproduce

Open dataset in spectrum viewer
Double click the name of the ROI in the table, and change it

### Expected Behaviour

Rename works

### Current Behaviour

Error message

### Context

Current main. Probably introduced in refactoring in  #1860

### Failure Logs

```
2023-09-04 11:52:44,567 [mantidimaging.gui.windows.main.view:L510] ERROR: Traceback (most recent call last):
  File "/home/vco13151/mantidimaging/mantidimaging/gui/windows/spectrum_viewer/view.py", line 128, in on_data_in_table_change
    on_visibility_change()
  File "/home/vco13151/mantidimaging/mantidimaging/gui/windows/spectrum_viewer/view.py", line 103, in on_visibility_change
    self.set_roi_alpha(255, roi_item)
  File "/home/vco13151/mantidimaging/mantidimaging/gui/windows/spectrum_viewer/view.py", line 235, in set_roi_alpha
    self.presenter.do_set_roi_alpha(self.roi_table_model.row_data(roi)[0], alpha)
  File "/home/vco13151/mantidimaging/mantidimaging/gui/windows/spectrum_viewer/presenter.py", line 143, in do_set_roi_alpha
    self.view.spectrum.set_roi_alpha(name, alpha)
  File "/home/vco13151/mantidimaging/mantidimaging/gui/windows/spectrum_viewer/spectrum_widget.py", line 161, in set_roi_alpha
    self.roi_dict[name].colour = self.roi_dict[name].colour[:3] + (alpha, )
KeyError: 'material_one'
```

**Comment by JackEAllen** [comment]
Can confirm if renaming the first roi is the first renaming operation within the table, this error will occur. 
I can also replicate if adding additional rois where the next operation is renaming the first roi if performed within quick succession from each other. I can not replicate if adding, then removing, then renaming the first roi.
