### ISSUE TITLE
ImportError for libssl.so.3 on linux with pyinstaller builds

### ISSUE THREAD

**Issue by samtygier-stfc** [mantidproject/mantidimaging#2300]
### Summary

When running a linux pyinstaller build I get
`ImportError: /home/sam/git/mantidimaging/packaging/dist/MantidImaging/_internal/libssl.so.3: version `OPENSSL_3.2.0' not found (required by /home/sam/git/mantidimaging/packaging/dist/MantidImaging/_internal/./libcurl.so.4)`
(full log below)

Seen on  #2299, but also happens on main.
This was also seen and supposedly fixed in #2276.

### Steps To Reproduce

Build with pyinstaller
Run `dist/MantidImaging/MantidImaging` from outside the mamba environment

### Expected Behaviour

It runs

### Current Behaviour
Import error

### Context

Current main, Python 3.10.14, Ubuntu 22.04

### Failure Logs
```
Traceback (most recent call last):
  File "mantidimaging/__main__.py", line 16, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 419, in exec_module
  File "mantidimaging/main.py", line 17, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 419, in exec_module
  File "mantidimaging/core/__init__.py", line 5, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 419, in exec_module
  File "mantidimaging/core/io/__init__.py", line 5, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 419, in exec_module
  File "mantidimaging/core/io/saver.py", line 10, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 419, in exec_module
  File "h5py/__init__.py", line 25, in <module>
ImportError: /home/sam/git/mantidimaging/packaging/dist/MantidImaging/_internal/libssl.so.3: version `OPENSSL_3.2.0' not found (required by /home/sam/git/mantidimaging/packaging/dist/MantidImaging/_internal/./libcurl.so.4)
[1367507] Failed to execute script '__main__' due to unhandled exception
```

**Comment by samtygier-stfc** [comment]
Judging by md5sum, the `libssl.so.3` that get include in `dist` by pyinstaller is from `/usr/lib/x86_64-linux-gnu/libssl.so.3` not `~/mambaforge/envs/mantidimaging-dev/lib/libssl.so.3`.

**Comment by samtygier-stfc** [comment]
Looks like the warnings
```
1335 WARNING: Conda distribution 'curl', dependency of 'curl', was not found. If you installed this distribution with pip then you may ignore this warning.
1335 WARNING: Conda distribution 'curl', dependency of 'curl', was not found. If you installed this distribution with pip then you may ignore this warning.
```
are warning about this problem.

Changing the `add_conda_dynamic_libs()` call from `curl` to `libcurl` helps.
