### ISSUE TITLE
Error on refining COR twice

### ISSUE THREAD

**Issue by WHTaylor** [mantidproject/mantidimaging#369]
To reproduce:
 - Open a stack
 - Generate COR
 - 'Refine' a result
 - Choose any option - refining then finish, or just finish immediately
 - Choose 'refine' again

Error message: <built-in function connectSlotsByName> returned a result with an error set

Stack trace:
```
[mantidimaging.gui.windows.cor_tilt.presenter:L64] ERROR: Notification handler failed
AttributeError: __getattribute__

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/wtaylor/mantidimaging/mantidimaging/gui/windows/cor_tilt/presenter.py", line 58, in notify
    self.do_refine_selected_cor()
  File "/home/wtaylor/mantidimaging/mantidimaging/gui/windows/cor_tilt/presenter.py", line 132, in do_refine_selected_cor
    dialog = CORInspectionDialogView(self.view, data=self.model.sample, slice_idx=slice_idx)
  File "/home/wtaylor/mantidimaging/mantidimaging/gui/dialogs/cor_inspection/view.py", line 16, in __init__
    parent, 'gui/ui/cor_inspection_dialog.ui')
  File "/home/wtaylor/mantidimaging/mantidimaging/gui/mvp_base/view.py", line 45, in __init__
    compile_ui(ui_file, self)
  File "/home/wtaylor/mantidimaging/mantidimaging/gui/utility/qt_helpers.py", line 40, in compile_ui
    return uic.loadUi(os.path.join(base_path, ui_file), qt_obj)
  File "/home/wtaylor/miniconda3/envs/cenv/lib/python3.7/site-packages/PyQt5/uic/__init__.py", line 226, in loadUi
    return DynamicUILoader(package).loadUi(uifile, baseinstance, resource_suffix)
  File "/home/wtaylor/miniconda3/envs/cenv/lib/python3.7/site-packages/PyQt5/uic/Loader/loader.py", line 72, in loadUi
    return self.parse(filename, resource_suffix, basedir)
  File "/home/wtaylor/miniconda3/envs/cenv/lib/python3.7/site-packages/PyQt5/uic/uiparser.py", line 1021, in parse
    actor(elem)
  File "/home/wtaylor/miniconda3/envs/cenv/lib/python3.7/site-packages/PyQt5/uic/uiparser.py", line 942, in createConnections
    QtCore.QMetaObject.connectSlotsByName(self.toplevelWidget)
SystemError: <built-in function connectSlotsByName> returned a result with an error set
```

**Comment by WHTaylor** [comment]
#339

**Comment by DTasev** [comment]
Can you check your PyQt5 version, supposedly 5.13.1 should have fixed that, and that's the version available on pip

**Comment by WHTaylor** [comment]
Installing 5.13.1 fixes. I'm not sure where my environment's PyQt5 was coming from before - it didn't show up under pip or conda, a bit spooky.
