### ISSUE TITLE
Intermitent StackVisualiserViewTest test failure

### ISSUE THREAD

**Issue by samtygier-stfc** [mantidproject/mantidimaging#805]
### Summary

StackVisualiserViewTest fails sometimes, dependent on test ordering.

### Steps To Reproduce

In my centos7 VM

`pytest -n 1 --count 1 --randomly-seed=274074171 -k StackVisualiserViewTest -v`

Seems to reliably trigger the failure. 

On my Ubuntu 20.04 laptop I need

`pytest -n 1 --count 1 --randomly-seed=3153455096 -k StackVisualiserViewTest -v`

Otherwise you can find a bad seed with
`while pytest -n 1 --count 1  -k StackVisualiserViewTest -v ; do echo ; done`

### Expected Behaviour

Tests pass

### Current Behaviour

`[gw0] [100%] PASSED mantidimaging/gui/windows/stack_visualiser/test/view_test.py::StackVisualiserViewTest::test_closeEvent_deletes_images_with_proj180_user_declined Fatal Python error: Segmentation fault`

### Context

Happens on master since the python 3.8 merge

### Failure Logs

```
(midev) [sam@localhost mantidimaging]$ pytest -n 1 --count 1 --randomly-seed=274074171 -k StackVisualiserViewTest -v
===================================================================== test session starts ======================================================================
platform linux -- Python 3.8.6, pytest-6.2.1, py-1.10.0, pluggy-0.13.1 -- /home/sam/miniconda3/envs/midev/bin/python
cachedir: .pytest_cache
Using --randomly-seed=274074171
rootdir: /home/sam/git/mantidimaging
plugins: forked-1.3.0, xdist-2.2.0, repeat-0.9.1, randomly-3.5.0, cov-2.10.1
[gw0] linux Python 3.8.6 cwd: /home/sam/git/mantidimaging
[gw0] Python 3.8.6 | packaged by conda-forge | (default, Dec 26 2020, 05:05:16)  -- [GCC 9.3.0]
gw0 [5]
scheduling tests via LoadScheduling

mantidimaging/gui/windows/stack_visualiser/test/view_test.py::StackVisualiserViewTest::test_closeEvent_deletes_images 
[gw0] [ 20%] PASSED mantidimaging/gui/windows/stack_visualiser/test/view_test.py::StackVisualiserViewTest::test_closeEvent_deletes_images 
mantidimaging/gui/windows/stack_visualiser/test/view_test.py::StackVisualiserViewTest::test_roi_changed_callback 
[gw0] [ 40%] PASSED mantidimaging/gui/windows/stack_visualiser/test/view_test.py::StackVisualiserViewTest::test_roi_changed_callback 
mantidimaging/gui/windows/stack_visualiser/test/view_test.py::StackVisualiserViewTest::test_name 
[gw0] [ 60%] PASSED mantidimaging/gui/windows/stack_visualiser/test/view_test.py::StackVisualiserViewTest::test_name 
mantidimaging/gui/windows/stack_visualiser/test/view_test.py::StackVisualiserViewTest::test_closeEvent_deletes_images_with_proj180_user_accepts 
[gw0] [ 80%] PASSED mantidimaging/gui/windows/stack_visualiser/test/view_test.py::StackVisualiserViewTest::test_closeEvent_deletes_images_with_proj180_user_accepts 
mantidimaging/gui/windows/stack_visualiser/test/view_test.py::StackVisualiserViewTest::test_closeEvent_deletes_images_with_proj180_user_declined 
[gw0] [100%] PASSED mantidimaging/gui/windows/stack_visualiser/test/view_test.py::StackVisualiserViewTest::test_closeEvent_deletes_images_with_proj180_user_declined Fatal Python error: Segmentation fault

Thread 0x00007f97ce0c1700 (most recent call first):
  File "/home/sam/miniconda3/envs/midev/lib/python3.8/site-packages/execnet/gateway_base.py", line 400 in read
  File "/home/sam/miniconda3/envs/midev/lib/python3.8/site-packages/execnet/gateway_base.py", line 432 in from_io
  File "/home/sam/miniconda3/envs/midev/lib/python3.8/site-packages/execnet/gateway_base.py", line 967 in _thread_receiver
  File "/home/sam/miniconda3/envs/midev/lib/python3.8/site-packages/execnet/gateway_base.py", line 220 in run
  File "/home/sam/miniconda3/envs/midev/lib/python3.8/site-packages/execnet/gateway_base.py", line 285 in _perform_spawn

Current thread 0x00007f97d5833740 (most recent call first):
  File "/home/sam/git/mantidimaging/mantidimaging/test_helpers/start_qapplication.py", line 58 in tearDownClass
  File "/home/sam/miniconda3/envs/midev/lib/python3.8/site-packages/_pytest/unittest.py", line 175 in fixture
  File "/home/sam/miniconda3/envs/midev/lib/python3.8/site-packages/_pytest/fixtures.py", line 941 in _teardown_yield_fixture
  File "/home/sam/miniconda3/envs/midev/lib/python3.8/site-packages/_pytest/fixtures.py", line 1027 in finish
  File "/home/sam/miniconda3/envs/midev/lib/python3.8/site-packages/_pytest/runner.py", line 395 in _callfinalizers
  File "/home/sam/miniconda3/envs/midev/lib/python3.8/site-packages/_pytest/runner.py", line 405 in _teardown_with_finalization
  File "/home/sam/miniconda3/envs/midev/lib/python3.8/site-packages/_pytest/runner.py", line 387 in _pop_and_teardown
  File "/home/sam/miniconda3/envs/midev/lib/python3.8/site-packages/_pytest/runner.py", line 427 in _teardown_towards
  File "/home/sam/miniconda3/envs/midev/lib/python3.8/site-packages/_pytest/runner.py", line 419 in teardown_exact
  File "/home/sam/miniconda3/envs/midev/lib/python3.8/site-packages/_pytest/runner.py", line 175 in pytest_runtest_teardown
  File "/home/sam/miniconda3/envs/midev/lib/python3.8/site-packages/pluggy/callers.py", line 187 in _multicall
  File "/home/sam/miniconda3/envs/midev/lib/python3.8/site-packages/pluggy/manager.py", line 84 in <lambda>
  File "/home/sam/miniconda3/envs/midev/lib/python3.8/site-packages/pluggy/manager.py", line 93 in _hookexec
  File "/home/sam/miniconda3/envs/midev/lib/python3.8/site-packages/pluggy/hooks.py", line 286 in __call__
  File "/home/sam/miniconda3/envs/midev/lib/python3.8/site-packages/_pytest/runner.py", line 255 in <lambda>
  File "/home/sam/miniconda3/envs/midev/lib/python3.8/site-packages/_pytest/runner.py", line 311 in from_call
  File "/home/sam/miniconda3/envs/midev/lib/python3.8/site-packages/_pytest/runner.py", line 254 in call_runtest_hook
  File "/home/sam/miniconda3/envs/midev/lib/python3.8/site-packages/_pytest/runner.py", line 215 in call_and_report
  File "/home/sam/miniconda3/envs/midev/lib/python3.8/site-packages/_pytest/runner.py", line 127 in runtestprotocol
  File "/home/sam/miniconda3/envs/midev/lib/python3.8/site-packages/_pytest/runner.py", line 109 in pytest_runtest_protocol
  File "/home/sam/miniconda3/envs/midev/lib/python3.8/site-packages/pluggy/callers.py", line 187 in _multicall
  File "/home/sam/miniconda3/envs/midev/lib/python3.8/site-packages/pluggy/manager.py", line 84 in <lambda>
  File "/home/sam/miniconda3/envs/midev/lib/python3.8/site-packages/pluggy/manager.py", line 93 in _hookexec
  File "/home/sam/miniconda3/envs/midev/lib/python3.8/site-packages/pluggy/hooks.py", line 286 in __call__
  File "/home/sam/miniconda3/envs/midev/lib/python3.8/site-packages/xdist/remote.py", line 89 in run_one_test
  File "/home/sam/miniconda3/envs/midev/lib/python3.8/site-packages/xdist/remote.py", line 75 in pytest_runtestloop
  File "/home/sam/miniconda3/envs/midev/lib/python3.8/site-packages/pluggy/callers.py", line 187 in _multicall
  File "/home/sam/miniconda3/envs/midev/lib/python3.8/site-packages/pluggy/manager.py", line 84 in <lambda>
  File "/home/sam/miniconda3/envs/midev/lib/python3.8/site-packages/pluggy/manager.py", line 93 in _hookexec
  File "/home/sam/miniconda3/envs/midev/lib/python3.8/site-packages/pluggy/hooks.py", line 286 in __call__
  File "/home/sam/miniconda3/envs/midev/lib/python3.8/site-packages/_pytest/main.py", line 323 in _main
  File "/home/sam/miniconda3/envs/midev/lib/python3.8/site-packages/_pytest/main.py", line 269 in wrap_session
  File "/home/sam/miniconda3/envs/midev/lib/python3.8/site-packages/_pytest/main.py", line 316 in pytest_cmdline_main
  File "/home/sam/miniconda3/envs/midev/lib/python3.8/site-packages/pluggy/callers.py", line 187 in _multicall
  File "/home/sam/miniconda3/envs/midev/lib/python3.8/site-packages/pluggy/manager.py", line 84 in <lambda>
  File "/home/sam/miniconda3/envs/midev/lib/python3.8/site-packages/pluggy/manager.py", line 93 in _hookexec
  File "/home/sam/miniconda3/envs/midev/lib/python3.8/site-packages/pluggy/hooks.py", line 286 in __call__
  File "/home/sam/miniconda3/envs/midev/lib/python3.8/site-packages/xdist/remote.py", line 239 in <module>
  File "/home/sam/miniconda3/envs/midev/lib/python3.8/site-packages/execnet/gateway_base.py", line 1084 in executetask
  File "/home/sam/miniconda3/envs/midev/lib/python3.8/site-packages/execnet/gateway_base.py", line 220 in run
  File "/home/sam/miniconda3/envs/midev/lib/python3.8/site-packages/execnet/gateway_base.py", line 285 in _perform_spawn
  File "/home/sam/miniconda3/envs/midev/lib/python3.8/site-packages/execnet/gateway_base.py", line 267 in integrate_as_primary_thread
  File "/home/sam/miniconda3/envs/midev/lib/python3.8/site-packages/execnet/gateway_base.py", line 1060 in serve
  File "/home/sam/miniconda3/envs/midev/lib/python3.8/site-packages/execnet/gateway_base.py", line 1554 in serve
  File "<string>", line 8 in <module>
  File "<string>", line 1 in <module>

[gw0] node down: Not properly terminated
[gw0] [100%] FAILED mantidimaging/gui/windows/stack_visualiser/test/view_test.py::StackVisualiserViewTest::test_closeEvent_deletes_images_with_proj180_user_declined 

replacing crashed worker gw0
[gw1] linux Python 3.8.6 cwd: /home/sam/git/mantidimaging
[gw1] Python 3.8.6 | packaged by conda-forge | (default, Dec 26 2020, 05:05:16)  -- [GCC 9.3.0]
gw1 ok
=========================================================================== FAILURES ===========================================================================
_________________________________________________ mantidimaging/gui/windows/stack_visualiser/test/view_test.py _________________________________________________
[gw0] linux -- Python 3.8.6 /home/sam/miniconda3/envs/midev/bin/python
worker 'gw0' crashed while running 'mantidimaging/gui/windows/stack_visualiser/test/view_test.py::StackVisualiserViewTest::test_closeEvent_deletes_images_with_proj180_user_declined'
======================================================================= warnings summary =======================================================================
../../miniconda3/envs/midev/lib/python3.8/site-packages/skimage/util/dtype.py:226
../../miniconda3/envs/midev/lib/python3.8/site-packages/skimage/util/dtype.py:226
  /home/sam/miniconda3/envs/midev/lib/python3.8/site-packages/skimage/util/dtype.py:226: DeprecationWarning: Converting `np.inexact` or `np.floating` to a dtype is deprecated. The current result is `float64` which is not strictly correct.
    dtypeobj_out = np.dtype(dtype)

../../miniconda3/envs/midev/lib/python3.8/site-packages/tomopy/recon/acceleration.py:57
../../miniconda3/envs/midev/lib/python3.8/site-packages/tomopy/recon/acceleration.py:57
  /home/sam/miniconda3/envs/midev/lib/python3.8/site-packages/tomopy/recon/acceleration.py:57: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
    import imp

-- Docs: https://docs.pytest.org/en/stable/warnings.html
=================================================================== short test summary info ====================================================================
FAILED mantidimaging/gui/windows/stack_visualiser/test/view_test.py::StackVisualiserViewTest::test_closeEvent_deletes_images_with_proj180_user_declined
=========================================================== 1 failed, 5 passed, 4 warnings in 5.13s ============================================================

```

**Comment by samtygier-stfc** [comment]
This is probably related to object lifetime issues, and the difference between how these are handled in python and qt. There are a couple of explanations of when this can go wrong:

- http://enki-editor.org/2014/08/23/Pyqt_mem_mgmt.html
- https://stefanoborini.com/pyqt-gotchas/

This is triggered when garbage collection happens (even if cg.collect not explicitly called). 

```
Thread 1 "python" received signal SIGSEGV, Segmentation fault.
_PyFunction_Vectorcall (func=0x7fff3a088700, stack=0x7fff1b650598, nargsf=1, kwnames=0x0)
    at /home/conda/feedstock_root/build_artifacts/python-split_1608956461873/work/Objects/call.c:395
395	/home/conda/feedstock_root/build_artifacts/python-split_1608956461873/work/Objects/call.c: No such file or directory.
(gdb) bt
#0  _PyFunction_Vectorcall (func=0x7fff3a088700, stack=0x7fff1b650598, nargsf=1, kwnames=0x0)
    at /home/conda/feedstock_root/build_artifacts/python-split_1608956461873/work/Objects/call.c:395
#1  0x00005555556666be in PyVectorcall_Call (kwargs=<optimised out>, tuple=<optimised out>, callable=0x7fff3a088700)
    at /home/conda/feedstock_root/build_artifacts/python-split_1608956461873/work/Objects/call.c:199
#2  PyObject_Call (callable=0x7fff3a088700, args=<optimised out>, kwargs=<optimised out>)
    at /home/conda/feedstock_root/build_artifacts/python-split_1608956461873/work/Objects/call.c:227
#3  0x00007fff6f8736e0 in PyQtSlot::call(_object*, _object*) const () from /home/sam/miniconda3/envs/midev-py38/lib/python3.8/site-packages/PyQt5/QtCore.abi3.so
#4  0x00007fff6f873bb8 in PyQtSlot::invoke(void**, _object*, void*, bool) const ()
   from /home/sam/miniconda3/envs/midev-py38/lib/python3.8/site-packages/PyQt5/QtCore.abi3.so
#5  0x00007fff6f873e40 in PyQtSlotProxy::unislot(void**) () from /home/sam/miniconda3/envs/midev-py38/lib/python3.8/site-packages/PyQt5/QtCore.abi3.so
#6  0x00007fff6f8748c7 in PyQtSlotProxy::qt_metacall(QMetaObject::Call, int, void**) ()
   from /home/sam/miniconda3/envs/midev-py38/lib/python3.8/site-packages/PyQt5/QtCore.abi3.so
#7  0x00007fff728faee7 in void doActivate<false>(QObject*, int, void**) ()
   from /home/sam/miniconda3/envs/midev-py38/lib/python3.8/site-packages/PyQt5/Qt/lib/libQt5Core.so.5
#8  0x00007fff728f445f in QObject::destroyed(QObject*) () from /home/sam/miniconda3/envs/midev-py38/lib/python3.8/site-packages/PyQt5/Qt/lib/libQt5Core.so.5
#9  0x00007fff728f8fd2 in QObject::~QObject() () from /home/sam/miniconda3/envs/midev-py38/lib/python3.8/site-packages/PyQt5/Qt/lib/libQt5Core.so.5
#10 0x00007fff6ea6a5dd in QGraphicsWidget::~QGraphicsWidget() ()
   from /home/sam/miniconda3/envs/midev-py38/lib/python3.8/site-packages/PyQt5/Qt/lib/libQt5Widgets.so.5
#11 0x00007fff6f027a19 in sipQGraphicsWidget::~sipQGraphicsWidget() ()
   from /home/sam/miniconda3/envs/midev-py38/lib/python3.8/site-packages/PyQt5/QtWidgets.abi3.so
#12 0x00007fff6ea21406 in QGraphicsItem::~QGraphicsItem() () from /home/sam/miniconda3/envs/midev-py38/lib/python3.8/site-packages/PyQt5/Qt/lib/libQt5Widgets.so.5
#13 0x00007fff6ea21583 in QGraphicsObject::~QGraphicsObject() ()
   from /home/sam/miniconda3/envs/midev-py38/lib/python3.8/site-packages/PyQt5/Qt/lib/libQt5Widgets.so.5
#14 0x00007fff6ea6a5dd in QGraphicsWidget::~QGraphicsWidget() ()
   from /home/sam/miniconda3/envs/midev-py38/lib/python3.8/site-packages/PyQt5/Qt/lib/libQt5Widgets.so.5
#15 0x00007fff6f027a19 in sipQGraphicsWidget::~sipQGraphicsWidget() ()
   from /home/sam/miniconda3/envs/midev-py38/lib/python3.8/site-packages/PyQt5/QtWidgets.abi3.so
#16 0x00007fff6ea34fce in QGraphicsScene::clear() () from /home/sam/miniconda3/envs/midev-py38/lib/python3.8/site-packages/PyQt5/Qt/lib/libQt5Widgets.so.5
#17 0x00007fff6ea36304 in QGraphicsScene::~QGraphicsScene() ()
   from /home/sam/miniconda3/envs/midev-py38/lib/python3.8/site-packages/PyQt5/Qt/lib/libQt5Widgets.so.5
#18 0x00007fff6f022149 in sipQGraphicsScene::~sipQGraphicsScene() () from /home/sam/miniconda3/envs/midev-py38/lib/python3.8/site-packages/PyQt5/QtWidgets.abi3.so
#19 0x00007fff728ee713 in QObjectPrivate::deleteChildren() () from /home/sam/miniconda3/envs/midev-py38/lib/python3.8/site-packages/PyQt5/Qt/lib/libQt5Core.so.5
#20 0x00007fff6e77e157 in QWidget::~QWidget() () from /home/sam/miniconda3/envs/midev-py38/lib/python3.8/site-packages/PyQt5/Qt/lib/libQt5Widgets.so.5
#21 0x00007fff6ea5dda4 in QGraphicsView::~QGraphicsView() () from /home/sam/miniconda3/envs/midev-py38/lib/python3.8/site-packages/PyQt5/Qt/lib/libQt5Widgets.so.5
#22 0x00007fff6f019f89 in sipQGraphicsView::~sipQGraphicsView() () from /home/sam/miniconda3/envs/midev-py38/lib/python3.8/site-packages/PyQt5/QtWidgets.abi3.so
#23 0x00007fff728ee713 in QObjectPrivate::deleteChildren() () from /home/sam/miniconda3/envs/midev-py38/lib/python3.8/site-packages/PyQt5/Qt/lib/libQt5Core.so.5
#24 0x00007fff6e77e157 in QWidget::~QWidget() () from /home/sam/miniconda3/envs/midev-py38/lib/python3.8/site-packages/PyQt5/Qt/lib/libQt5Widgets.so.5
#25 0x00007fff6efe7de9 in sipQSplitter::~sipQSplitter() () from /home/sam/miniconda3/envs/midev-py38/lib/python3.8/site-packages/PyQt5/QtWidgets.abi3.so
#26 0x00007fff728ee713 in QObjectPrivate::deleteChildren() () from /home/sam/miniconda3/envs/midev-py38/lib/python3.8/site-packages/PyQt5/Qt/lib/libQt5Core.so.5
#27 0x00007fff6e77e157 in QWidget::~QWidget() () from /home/sam/miniconda3/envs/midev-py38/lib/python3.8/site-packages/PyQt5/Qt/lib/libQt5Widgets.so.5
#28 0x00007fff6f0721d9 in sipQWidget::~sipQWidget() () from /home/sam/miniconda3/envs/midev-py38/lib/python3.8/site-packages/PyQt5/QtWidgets.abi3.so
#29 0x00007fff6fb87309 in forgetObject (sw=sw@entry=0x7fff1b7e55e0) at siplib.c:11384
#30 0x00007fff6fb87349 in sipWrapper_dealloc (self=0x7fff1b7e55e0) at siplib.c:11003
#31 0x00005555556d5575 in subtype_dealloc (self=0x7fff1b7e55e0)
    at /home/conda/feedstock_root/build_artifacts/python-split_1608956461873/work/Objects/typeobject.c:1292
#32 0x0000555555641e64 in _Py_DECREF (filename=<synthetic pointer>, lineno=541, op=<optimised out>)
    at /home/conda/feedstock_root/build_artifacts/python-split_1608956461873/work/Include/object.h:478
... 

#41 0x00005555556612c4 in delete_garbage (state=<optimised out>, state=<optimised out>, old=0x5555558f4570 <_PyRuntime+416>, collectable=0x7fffffff70b0)
    at /home/conda/feedstock_root/build_artifacts/python-split_1608956461873/work/Modules/gcmodule.c:948
#42 collect (generation=2, n_collected=0x7fffffff7198, n_uncollectable=0x7fffffff71a0, nofail=0, state=0x5555558f4528 <_PyRuntime+344>)
    at /home/conda/feedstock_root/build_artifacts/python-split_1608956461873/work/Modules/gcmodule.c:1123
#43 0x0000555555746929 in collect_with_callback (generation=2, state=0x5555558f4528 <_PyRuntime+344>)
    at /home/conda/feedstock_root/build_artifacts/python-split_1608956461873/work/Modules/gcmodule.c:1240

```

I've try a few things without success. Still investigating.
