### ISSUE TITLE
Occasional failure in AsyncTaskDialogPresenterTest.test_basic_happy_case

### ISSUE THREAD

**Issue by samtygier-stfc** [mantidproject/mantidimaging#806]
### Summary

Found by running the tests in a loop

`while pytest -n 4 --count 1 -k 'not StackVisualiserViewTest' ; do echo ; done`

### Steps To Reproduce

I have seen it a couple of times, but still searching for a reliable method to reproduce.

### Expected Behaviour

Tests always pass

### Current Behaviour

`mantidimaging/gui/dialogs/async_task/test/presenter_test.py:28: AssertionError`

### Context

On current master 7980b3416e3bcdec0b34567d73aeb4c3e39bad9e

### Failure Logs

```
platform linux -- Python 3.8.6, pytest-6.2.1, py-1.10.0, pluggy-0.13.1
Using --randomly-seed=3415171490
rootdir: /home/sam/git/mantidimaging
plugins: forked-1.3.0, xdist-2.2.0, repeat-0.9.1, randomly-3.5.0, cov-2.10.1
gw0 [495] / gw1 [495] / gw2 [495] / gw3 [495]
.............................................................................................................................. [ 25%]
.............................................................................................................................. [ 50%]
............................................................................................sssssssF...........s.....ss....... [ 76%]
.....................................................................................................................          [100%]
============================================================== FAILURES ==============================================================
_________________________________________ AsyncTaskDialogPresenterTest.test_basic_happy_case _________________________________________
[gw0] linux -- Python 3.8.6 /home/sam/miniconda3/envs/midev/bin/python

self = <mantidimaging.gui.dialogs.async_task.test.presenter_test.AsyncTaskDialogPresenterTest testMethod=test_basic_happy_case>

    def test_basic_happy_case(self):
        def f(a, b):
            time.sleep(0.1)
            return a + b
    
        v = mock.create_autospec(AsyncTaskDialogView)
    
        p = AsyncTaskDialogPresenter(v)
        p.set_task(f)
        p.set_parameters([5], {'b': 4})
        self.assertFalse(p.task_is_running)
    
        p.notify(Notification.START)
        v.show.assert_called_once()
>       self.assertTrue(p.task_is_running)
E       AssertionError: False is not true

mantidimaging/gui/dialogs/async_task/test/presenter_test.py:28: AssertionError
-------------------------------------------------------- Captured stdout call --------------------------------------------------------
2021-01-08 14:29:10,549 [mantidimaging.gui.dialogs.async_task.task:L48] ERROR: Failed to execute task
Traceback (most recent call last):
  File "/home/sam/git/mantidimaging/mantidimaging/gui/dialogs/async_task/task.py", line 45, in run
    self.result = call_with_known_parameters(self.task_function, *self.args, **self.kwargs)
  File "/home/sam/git/mantidimaging/mantidimaging/core/utility/func_call.py", line 11, in call_with_known_parameters
    return func(**ka)
TypeError: f() missing 2 required positional arguments: 'a' and 'b'
--------------------------------------------------------- Captured log call ----------------------------------------------------------
ERROR    mantidimaging.gui.dialogs.async_task.task:task.py:48 Failed to execute task
Traceback (most recent call last):
  File "/home/sam/git/mantidimaging/mantidimaging/gui/dialogs/async_task/task.py", line 45, in run
    self.result = call_with_known_parameters(self.task_function, *self.args, **self.kwargs)
  File "/home/sam/git/mantidimaging/mantidimaging/core/utility/func_call.py", line 11, in call_with_known_parameters
    return func(**ka)
TypeError: f() missing 2 required positional arguments: 'a' and 'b'

```

**Comment by samtygier-stfc** [comment]
I've not seen recently and can't reproduce on master. Closing until it reoccurs.
