### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'availableGeometry'

### ISSUE THREAD

**Issue by samtygier-stfc** [mantidproject/mantidimaging#816]
### Summary

When opening the operations window I get the message

`AttributeError: 'NoneType' object has no attribute 'availableGeometry'`

Full trace is

```
2021-01-13 14:32:04,515 [mantidimaging.gui.windows.main.view:L342] ERROR: Traceback (most recent call last):
  File "/home/sam/git/mantidimaging/mantidimaging/gui/windows/main/view.py", line 252, in show_filters_window
    self.filters = FiltersWindowView(self)
  File "/home/sam/git/mantidimaging/mantidimaging/gui/windows/operations/view.py", line 75, in __init__
    self.previews = FilterPreviews(self)
  File "/home/sam/git/mantidimaging/mantidimaging/gui/windows/operations/filter_previews.py", line 44, in __init__
    self.ALLOWED_HEIGHT: QRect = QGuiApplication.screenAt(widget_location).availableGeometry().height() * 0.8
AttributeError: 'NoneType' object has no attribute 'availableGeometry'
```

### Steps To Reproduce

Open MI. Load a stack. Open Operations from Workflow menu

### Expected Behaviour

Shows operations window

### Current Behaviour

Error message

### Context

I see this on master and release-2.0. 

I started getting this after switching to s dual display set up on new laptop. Also using MATE desktop.

### Failure Logs

Trace above

**Comment by samtygier-stfc** [comment]
This depends on how much screens are arranged. In the top case this works fine, in the bottom case it fails. 

![Screenshot at 2021-01-13 screen layout](https://user-images.githubusercontent.com/74248560/104472601-0584de00-55b4-11eb-9d2b-f0aaf66a4df1.png)

`self.mapToGlobal(QPoint(self.width() / 2, 0))` always returns `PyQt5.QtCore.QPoint(50, 0)` no matter where the window is. So in the second case gives a global location above the smaller screen.

Sam J suggests using `QApplication.primaryScreen()` as a fall back
