### ISSUE TITLE
Missing image data in main window

### ISSUE THREAD

**Issue by samtygier-stfc** [mantidproject/mantidimaging#862]
### Summary

Reported happening with 2.0 on IDasS. 

"At one point the all values in a reconstructed stack were changed to “NaN”. I did close and reopen the Reconstruction window but that shouldn’t have deleted the data (without removing the stack). Strangely enough I still see the reconstructed images in the operations GUI."

The info text at the bottom of the image view shows NaN for every pixel. The histogram still shows data. Opening the operations window and selecting the stack shows that the data is still there.

### Steps To Reproduce

Happened to the reconstructed stack.

### Expected Behaviour

Data visible in the main window.

### Current Behaviour

Data not shown, but appears to still be present in other parts of the UI

### Context

IDaaS. MI 2.0

### Failure Logs

```
2021-02-18 11:35:40,182 [py.warnings:L174] WARNING: /opt/miniconda/envs/mantidimaging/lib/python3.7/site-packages/pyqtgraph/imageview/ImageView.py:643: RuntimeWarning: All-NaN slice encountered

2021-02-18 11:35:42,683 [mantidimaging.gui.mvp_base.presenter:L24] ERROR: Presenter error: Cannot set range [nan, nan]
Traceback (most recent call last):
  File "/opt/miniconda/envs/mantidimaging/lib/python3.7/site-packages/mantidimaging/gui/windows/stack_visualiser/presenter.py", line 57, in notify
    self.toggle_image_mode()
  File "/opt/miniconda/envs/mantidimaging/lib/python3.7/site-packages/mantidimaging/gui/windows/stack_visualiser/presenter.py", line 100, in toggle_image_mode
    self.refresh_image()
  File "/opt/miniconda/envs/mantidimaging/lib/python3.7/site-packages/mantidimaging/gui/windows/stack_visualiser/presenter.py", line 77, in refresh_image
    else self.images.data
  File "/opt/miniconda/envs/mantidimaging/lib/python3.7/site-packages/mantidimaging/gui/windows/stack_visualiser/view.py", line 103, in image
    self.image_view.setImage(to_display)
  File "/opt/miniconda/envs/mantidimaging/lib/python3.7/site-packages/pyqtgraph/imageview/ImageView.py", line 322, in setImage
    self.updateImage(autoHistogramRange=autoHistogramRange)
  File "/opt/miniconda/envs/mantidimaging/lib/python3.7/site-packages/pyqtgraph/imageview/ImageView.py", line 717, in updateImage
    self.ui.histogram.setHistogramRange(self.levelMin, self.levelMax)
  File "/opt/miniconda/envs/mantidimaging/lib/python3.7/site-packages/pyqtgraph/graphicsItems/HistogramLUTItem.py", line 155, in setHistogramRange
    self.vb.setYRange(mn, mx, padding)
  File "/opt/miniconda/envs/mantidimaging/lib/python3.7/site-packages/pyqtgraph/graphicsItems/ViewBox/ViewBox.py", line 649, in setYRange
    self.setRange(yRange=[min, max], update=update, padding=padding)
  File "/opt/miniconda/envs/mantidimaging/lib/python3.7/site-packages/pyqtgraph/graphicsItems/ViewBox/ViewBox.py", line 571, in setRange
    raise Exception("Cannot set range [%s, %s]" % (str(mn), str(mx)))
Exception: Cannot set range [nan, nan]
Traceback (most recent call last):
  File "/opt/miniconda/envs/mantidimaging/lib/python3.7/site-packages/mantidimaging/gui/windows/stack_visualiser/presenter.py", line 57, in notify
    self.toggle_image_mode()
  File "/opt/miniconda/envs/mantidimaging/lib/python3.7/site-packages/mantidimaging/gui/windows/stack_visualiser/presenter.py", line 100, in toggle_image_mode
    self.refresh_image()
  File "/opt/miniconda/envs/mantidimaging/lib/python3.7/site-packages/mantidimaging/gui/windows/stack_visualiser/presenter.py", line 77, in refresh_image
    else self.images.data
  File "/opt/miniconda/envs/mantidimaging/lib/python3.7/site-packages/mantidimaging/gui/windows/stack_visualiser/view.py", line 103, in image
    self.image_view.setImage(to_display)
  File "/opt/miniconda/envs/mantidimaging/lib/python3.7/site-packages/pyqtgraph/imageview/ImageView.py", line 322, in setImage
    self.updateImage(autoHistogramRange=autoHistogramRange)
  File "/opt/miniconda/envs/mantidimaging/lib/python3.7/site-packages/pyqtgraph/imageview/ImageView.py", line 717, in updateImage
    self.ui.histogram.setHistogramRange(self.levelMin, self.levelMax)
  File "/opt/miniconda/envs/mantidimaging/lib/python3.7/site-packages/pyqtgraph/graphicsItems/HistogramLUTItem.py", line 155, in setHistogramRange
    self.vb.setYRange(mn, mx, padding)
  File "/opt/miniconda/envs/mantidimaging/lib/python3.7/site-packages/pyqtgraph/graphicsItems/ViewBox/ViewBox.py", line 649, in setYRange
    self.setRange(yRange=[min, max], update=update, padding=padding)
  File "/opt/miniconda/envs/mantidimaging/lib/python3.7/site-packages/pyqtgraph/graphicsItems/ViewBox/ViewBox.py", line 571, in setRange
    raise Exception("Cannot set range [%s, %s]" % (str(mn), str(mx)))
Exception: Cannot set range [nan, nan]
2021-02-18 11:35:42,684 [mantidimaging.gui.windows.stack_visualiser.presenter:L66] ERROR: Notification handler failed
Traceback (most recent call last):
  File "/opt/miniconda/envs/mantidimaging/lib/python3.7/site-packages/mantidimaging/gui/windows/stack_visualiser/presenter.py", line 57, in notify
    self.toggle_image_mode()
  File "/opt/miniconda/envs/mantidimaging/lib/python3.7/site-packages/mantidimaging/gui/windows/stack_visualiser/presenter.py", line 100, in toggle_image_mode
    self.refresh_image()
  File "/opt/miniconda/envs/mantidimaging/lib/python3.7/site-packages/mantidimaging/gui/windows/stack_visualiser/presenter.py", line 77, in refresh_image
    else self.images.data
  File "/opt/miniconda/envs/mantidimaging/lib/python3.7/site-packages/mantidimaging/gui/windows/stack_visualiser/view.py", line 103, in image
    self.image_view.setImage(to_display)
  File "/opt/miniconda/envs/mantidimaging/lib/python3.7/site-packages/pyqtgraph/imageview/ImageView.py", line 322, in setImage
    self.updateImage(autoHistogramRange=autoHistogramRange)
  File "/opt/miniconda/envs/mantidimaging/lib/python3.7/site-packages/pyqtgraph/imageview/ImageView.py", line 717, in updateImage
    self.ui.histogram.setHistogramRange(self.levelMin, self.levelMax)
  File "/opt/miniconda/envs/mantidimaging/lib/python3.7/site-packages/pyqtgraph/graphicsItems/HistogramLUTItem.py", line 155, in setHistogramRange
    self.vb.setYRange(mn, mx, padding)
  File "/opt/miniconda/envs/mantidimaging/lib/python3.7/site-packages/pyqtgraph/graphicsItems/ViewBox/ViewBox.py", line 649, in setYRange
    self.setRange(yRange=[min, max], update=update, padding=padding)
  File "/opt/miniconda/envs/mantidimaging/lib/python3.7/site-packages/pyqtgraph/graphicsItems/ViewBox/ViewBox.py", line 571, in setRange
    raise Exception("Cannot set range [%s, %s]" % (str(mn), str(mx)))
Exception: Cannot set range [nan, nan]
```

### Screenshot(s)

![image](https://user-images.githubusercontent.com/74248560/108507339-13640800-72b2-11eb-9fd0-467943b6c22f.png)

note the "value = nan"

**Comment by samtygier-stfc** [comment]
I have not managed to reproduce on master. Suspect that the change from SharedArray to multiprocessing.Array has solved this. Closing, but can reopen if it is found in nightly or 2.1.
