### ISSUE TITLE
RuntimeError from apply button

### ISSUE THREAD

**Issue by DolicaAkelloEgwel** [mantidproject/mantidimaging#889]
### Summary

Opening and closing operations window leads to an exception.

### Steps To Reproduce

1. Open a dataset
2. Open and close operations window
3. Open operations window again
4. Run an operation

### Expected Behaviour

No exception.

### Context

Branch: master
OS: Ubuntu 20.04.2 LTS x86_64

### Failure Logs

```
2021-03-15 16:26:19,536 [mantidimaging.gui.windows.main.view:L357] ERROR: Traceback (most recent call last):
  File "/home/work/mantidimaging/mantidimaging/gui/windows/operations/presenter.py", line 61, in <lambda>
    lambda: self._set_apply_buttons_enabled(self.prev_apply_single_state, self.prev_apply_all_state))
  File "/home/work/mantidimaging/mantidimaging/gui/windows/operations/presenter.py", line 311, in _set_apply_buttons_enabled
    self.view.applyButton.setEnabled(apply_single_enabled)
RuntimeError: wrapped C/C++ object of type QPushButton has been deleted
```

**Comment by samtygier-stfc** [comment]
#890 also fixes this
