### ISSUE TITLE
Rebin Operation failed: '<' not supported between instances of 'Progress' and 'int'

### ISSUE THREAD

**Issue by samtygier-stfc** [mantidproject/mantidimaging#901]
### Summary

Running Rebin operation gives the error

`Operation failed: '<' not supported between instances of 'Progress' and 'int'`

### Steps To Reproduce

Open a dataset, open ops window
Select Rebin
Press Apply to Stack

### Expected Behaviour

Rebins the dataset

### Current Behaviour

Error message, and backtrace below

### Context

Happens on master, worked fine in 2.0

### Failure Logs
2021-03-25 16:26:07,810 [mantidimaging.core.parallel.utility:L113] INFO: Running async on Progress(
ProgressHistory(time=95875.446305392, step=0, msg='init | 0/1 | Time: 00:00:00, ETA: 00:00:00')) cores
2021-03-25 16:26:07,811 [mantidimaging.gui.dialogs.async_task.task:L48] ERROR: Failed to execute task
Traceback (most recent call last):
  File "/home/sam/git/mantidimaging/mantidimaging/gui/dialogs/async_task/task.py", line 45, in run
    self.result = call_with_known_parameters(self.task_function, *self.args, **self.kwargs)
  File "/home/sam/git/mantidimaging/mantidimaging/core/utility/func_call.py", line 11, in call_with_known_parameters
    return func(**ka)
  File "/home/sam/git/mantidimaging/mantidimaging/gui/windows/operations/model.py", line 101, in apply_to_stacks
    self.apply_to_images(stack.presenter.images, progress=progress)
  File "/home/sam/git/mantidimaging/mantidimaging/gui/windows/operations/model.py", line 113, in apply_to_images
    exec_func(images)
  File "/home/sam/git/mantidimaging/mantidimaging/core/operations/rebin/rebin.py", line 59, in filter_func
    ps.execute(f, sample.shape[0], cores, "Applying Rebin", progress)
  File "/home/sam/git/mantidimaging/mantidimaging/core/parallel/shared.py", line 114, in execute
    pu.execute_impl(num_operations, partial_func, cores, chunksize, progress, msg)
  File "/home/sam/git/mantidimaging/mantidimaging/core/parallel/utility.py", line 122, in execute_impl
    with Pool(cores) as pool:
  File "/home/sam/miniconda3/envs/midev-py38/lib/python3.8/multiprocessing/pool.py", line 204, in __init__
    if processes < 1:
TypeError: '<' not supported between instances of 'Progress' and 'int'

**Comment by samtygier-stfc** [comment]
Git bisect leads to a6c7ddcf7585ff0b64f7adf261607f40dd4989f9
