### ISSUE TITLE
median: NameError: name 'cp' is not defined

### ISSUE THREAD

**Issue by samtygier-stfc** [mantidproject/mantidimaging#939]
### Summary

Enabling 'Use GPU' on the median filter on IDAaaS give the an error:  NameError: name 'cp' is not defined

### Steps To Reproduce

On IDAaaS, open the Nightly build
Open a dataset, open operations window, choose median operation.
Tick the 'Use GPU' box

### Expected Behaviour

Filter works

### Current Behaviour

Error message

### Context
Happening with 2.1.0rc55

### Failure Logs

```
2021-04-19 10:42:11,675 [mantidimaging.gui.mvp_base.presenter:L24] ERROR: Presenter error: Error applying filter for preview: name 'cp' is not defined
Traceback (most recent call last):
  File "/opt/miniconda/envs/mantidimaging_unstable/lib/python3.8/site-packages/mantidimaging/gui/windows/operations/presenter.py", line 258, in do_update_previews
    self.model.apply_to_images(subset)
  File "/opt/miniconda/envs/mantidimaging_unstable/lib/python3.8/site-packages/mantidimaging/gui/windows/operations/model.py", line 120, in apply_to_images
    exec_func(images)
  File "/opt/miniconda/envs/mantidimaging_unstable/lib/python3.8/site-packages/mantidimaging/core/operations/median_filter/median_filter.py", line 54, in filter_func
    data = _execute_gpu(data.data, size, mode, progress)
  File "/opt/miniconda/envs/mantidimaging_unstable/lib/python3.8/site-packages/mantidimaging/core/operations/median_filter/median_filter.py", line 118, in _execute_gpu
    cuda = gpu.CudaExecuter(data.dtype)
  File "/opt/miniconda/envs/mantidimaging_unstable/lib/python3.8/site-packages/mantidimaging/core/gpu/utility.py", line 193, in __init__
    median_filter_module = cp.RawModule(code=loaded_from_source)
NameError: name 'cp' is not defined
```

**Comment by samtygier-stfc** [comment]
cupy should probably be added to `conda/meta.yaml`

However if I install it with `conda install cupy` on IDAaaS I then get the following error.

```
Traceback (most recent call last):
  File "/opt/miniconda/envs/mantidimaging_unstable/lib/python3.8/site-packages/mantidimaging/gui/windows/operations/presenter.py", line 258, in do_update_previews
    self.model.apply_to_images(subset)
  File "/opt/miniconda/envs/mantidimaging_unstable/lib/python3.8/site-packages/mantidimaging/gui/windows/operations/model.py", line 120, in apply_to_images
    exec_func(images)
  File "/opt/miniconda/envs/mantidimaging_unstable/lib/python3.8/site-packages/mantidimaging/core/operations/median_filter/median_filter.py", line 54, in filter_func
    data = _execute_gpu(data.data, size, mode, progress)
  File "/opt/miniconda/envs/mantidimaging_unstable/lib/python3.8/site-packages/mantidimaging/core/operations/median_filter/median_filter.py", line 118, in _execute_gpu
    cuda = gpu.CudaExecuter(data.dtype)
  File "/opt/miniconda/envs/mantidimaging_unstable/lib/python3.8/site-packages/mantidimaging/core/gpu/utility.py", line 194, in __init__
    self.single_image_median_filter = median_filter_module.get_function("two_dimensional_median_filter")
  File "cupy/core/raw.pyx", line 464, in cupy.core.raw.RawModule.get_function
  File "cupy/core/raw.pyx", line 89, in cupy.core.raw.RawKernel.kernel.__get__
  File "cupy/core/raw.pyx", line 106, in cupy.core.raw.RawKernel._kernel
  File "cupy/_util.pyx", line 59, in cupy._util.memoize.decorator.ret
  File "cupy/core/raw.pyx", line 525, in cupy.core.raw._get_raw_module
  File "cupy/core/core.pyx", line 1838, in cupy.core.core.compile_with_cache
  File "cupy/core/core.pyx", line 1894, in cupy.core.core.compile_with_cache
  File "/opt/miniconda/envs/mantidimaging_unstable/lib/python3.8/site-packages/cupy/cuda/compiler.py", line 370, in compile_with_cache
    return _compile_with_cache_cuda(
  File "/opt/miniconda/envs/mantidimaging_unstable/lib/python3.8/site-packages/cupy/cuda/compiler.py", line 479, in _compile_with_cache_cuda
    mod.load(cubin)
  File "cupy/cuda/function.pyx", line 241, in cupy.cuda.function.Module.load
  File "cupy/cuda/function.pyx", line 243, in cupy.cuda.function.Module.load
  File "cupy_backends/cuda/api/driver.pyx", line 246, in cupy_backends.cuda.api.driver.moduleLoadData
  File "cupy_backends/cuda/api/driver.pyx", line 124, in cupy_backends.cuda.api.driver.check_status
cupy_backends.cuda.api.driver.CUDADriverError: CUDA_ERROR_INVALID_PTX: a PTX JIT compilation failed
```

**Comment by samtygier-stfc** [comment]
I think the PTX issues is due to missing or mismatching cuda dev tools. "cudatoolkit package from conda-forge does not include the nvcc compiler toolchain"

Installing cupy and cudatoolkit through conda or pip makes no difference.
 
The Tomography IDAaaS instances don't currently the cudtoolkit or nvcc installed. It is straight forward to add cuda-repo-rhel7-9-2-local rpm to the install and install cuda from that, but the error persists. Probably because we use 10.2 conda packages.

Manually installingg10.2 from https://developer.nvidia.com/cuda-10.2-download-archive mismatches with installed kernel which is hard to change.
